# Python final term project
1. tool used : pandas ,numpy ,matplotlib
2. dataset : "PCOS_extended_dataset.csv"
3. dataset source :Kaggle — PCOS Dataset by cm037divya 
4. source link :https://www.kaggle.com/datasets/cm037divya/pcos-dataset

In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tkinter import Tk
from tkinter.filedialog import askopenfilename

#show korbe current working folder 
print("Current working folder:")
print(Path.cwd())

#ekhane dataset ta load korar cesta korbe 
csv_file = Path("PCOS_extended_dataset.csv")

#jodi na khuje pai tahole file picker diye try korbe
if not csv_file.exists():
    print("\nCSV file not found in current folder.")
    print("Please select the CSV file manually.")

    root = Tk()
    root.withdraw()
    root.attributes("-topmost", True)

    selected_file = askopenfilename(
        title="Select PCOS_extended_dataset.csv",
        filetypes=[("CSV files", "*.csv")]
    )

    root.destroy()

    if selected_file == "":
        raise FileNotFoundError("No file selected. Please choose your dataset CSV file.")

    csv_file = Path(selected_file)

#ekhane dataset ta read korbe
df = pd.read_csv(csv_file)

print("\nDataset loaded successfully!")
print("File used:", csv_file)
print("Original dataset shape:", df.shape)

df.head()

Current working folder:
c:\Users\Asus\Desktop\final project

CSV file not found in current folder.
Please select the CSV file manually.

Dataset loaded successfully!
File used: C:\Users\Asus\Desktop\pcos_data_analysis_project_easy\pcos_project_easy\PCOS_extended_dataset.csv
Original dataset shape: (2000, 44)

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
0,193,193,0,30,69.979147,167.708055,23.185569,12,72,22,...,1,0.0,1,105.483401,76.096379,2,4,10.0,13.0,6.176029
1,360,360,0,36,63.711688,154.055877,25.441392,13,70,18,...,1,0.0,1,115.883740,79.117243,2,3,13.0,11.0,6.824718
2,10,10,0,36,51.848631,149.059804,23.928264,15,80,20,...,0,0.0,0,112.219711,80.919417,1,1,14.0,17.0,2.568691
3,278,278,1,29,66.893988,148.628036,27.894935,15,72,18,...,0,0.0,1,104.619624,69.902681,1,1,12.0,14.0,9.962732
4,71,71,0,33,52.536198,150.767409,23.079564,13,72,18,...,0,0.0,0,99.175454,70.330461,5,2,11.5,4.7,6.655190

# Data understanding

In [2]:
print("print first 5 rows")
display(df.head()) #first 5 ta row show korve
print("display last 5 columns") #last 5 column show korbe
display(df.tail())
print("how many rows and columns")
display(df.shape)
print("column names")
display(df.columns.tolist()) #index k ekti normal python list e rupantor kore 
print("\n data types:")
print(df.dtypes) #ki data type seta ber kore 
print("summery statistic")
display(df.describe()) #summery kore dataset er
print("\n missing values")
display(df.isnull().sum()) #check kore missing values 
print("\nDuplicate values")
display(df.duplicated().sum())

print first 5 rows

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
0,193,193,0,30,69.979147,167.708055,23.185569,12,72,22,...,1,0.0,1,105.483401,76.096379,2,4,10.0,13.0,6.176029
1,360,360,0,36,63.711688,154.055877,25.441392,13,70,18,...,1,0.0,1,115.883740,79.117243,2,3,13.0,11.0,6.824718
2,10,10,0,36,51.848631,149.059804,23.928264,15,80,20,...,0,0.0,0,112.219711,80.919417,1,1,14.0,17.0,2.568691
3,278,278,1,29,66.893988,148.628036,27.894935,15,72,18,...,0,0.0,1,104.619624,69.902681,1,1,12.0,14.0,9.962732
4,71,71,0,33,52.536198,150.767409,23.079564,13,72,18,...,0,0.0,0,99.175454,70.330461,5,2,11.5,4.7,6.655190

display last 5 columns

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
1995,87,87,0,31,66.948922,155.976858,26.662263,15,74,18,...,0,0.0,0,120.323951,83.738573,8,10,15.0,13.0,9.816150
1996,508,508,0,37,64.592788,151.979792,27.681715,11,74,20,...,0,1.0,0,109.738395,76.083303,6,6,19.0,19.0,7.930382
1997,166,166,0,32,47.750129,148.596447,20.041406,11,73,26,...,1,1.0,0,109.570220,61.778231,5,5,14.0,13.0,6.832224
1998,266,266,0,40,31.869660,152.589988,13.793101,15,72,20,...,0,1.0,1,119.456176,79.410616,6,5,18.0,17.0,7.636086
1999,89,89,1,22,70.206568,167.852724,24.791898,13,74,20,...,0,0.0,0,108.275182,76.251829,10,13,15.0,16.0,9.950989

how many rows and columns

(2000, 44)

column names

['Sl. No',
 'Patient File No.',
 'PCOS (Y/N)',
 ' Age (yrs)',
 'Weight (Kg)',
 'Height(Cm) ',
 'BMI',
 'Blood Group',
 'Pulse rate(bpm) ',
 'RR (breaths/min)',
 'Hb(g/dl)',
 'Cycle(R/I)',
 'Cycle length(days)',
 'Marraige Status (Yrs)',
 'Pregnant(Y/N)',
 'No. of abortions',
 '  I   beta-HCG(mIU/mL)',
 'II    beta-HCG(mIU/mL)',
 'FSH(mIU/mL)',
 'LH(mIU/mL)',
 'FSH/LH',
 'Hip(inch)',
 'Waist(inch)',
 'Waist:Hip Ratio',
 'TSH (mIU/L)',
 'AMH(ng/mL)',
 'PRL(ng/mL)',
 'Vit D3 (ng/mL)',
 'PRG(ng/mL)',
 'RBS(mg/dl)',
 'Weight gain(Y/N)',
 'hair growth(Y/N)',
 'Skin darkening (Y/N)',
 'Hair loss(Y/N)',
 'Pimples(Y/N)',
 'Fast food (Y/N)',
 'Reg.Exercise(Y/N)',
 'BP _Systolic (mmHg)',
 'BP _Diastolic (mmHg)',
 'Follicle No. (L)',
 'Follicle No. (R)',
 'Avg. F size (L) (mm)',
 'Avg. F size (R) (mm)',
 'Endometrium (mm)']

 data types:
Sl. No                      int64
Patient File No.            int64
PCOS (Y/N)                  int64
 Age (yrs)                  int64
Weight (Kg)               float64
Height(Cm)                float64
BMI                       float64
Blood Group                 int64
Pulse rate(bpm)             int64
RR (breaths/min)            int64
Hb(g/dl)                  float64
Cycle(R/I)                  int64
Cycle length(days)          int64
Marraige Status (Yrs)     float64
Pregnant(Y/N)               int64
No. of abortions            int64
  I   beta-HCG(mIU/mL)    float64
II    beta-HCG(mIU/mL)     object
FSH(mIU/mL)               float64
LH(mIU/mL)                float64
FSH/LH                    float64
Hip(inch)                   int64
Waist(inch)                 int64
Waist:Hip Ratio           float64
TSH (mIU/L)               float64
AMH(ng/mL)                 object
PRL(ng/mL)                float64
Vit D3 (ng/mL)            float64
PRG(ng/mL)                float64
RBS(mg/dl)                float64
Weight gain(Y/N)            int64
hair growth(Y/N)            int64
Skin darkening (Y/N)        int64
Hair loss(Y/N)              int64
Pimples(Y/N)                int64
Fast food (Y/N)           float64
Reg.Exercise(Y/N)           int64
BP _Systolic (mmHg)       float64
BP _Diastolic (mmHg)      float64
Follicle No. (L)            int64
Follicle No. (R)            int64
Avg. F size (L) (mm)      float64
Avg. F size (R) (mm)      float64
Endometrium (mm)          float64
dtype: object
summery statistic

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.00000,2000.000000,2000.000000,2000.000000
mean,266.633000,266.633000,0.304000,31.35400,59.527068,156.416496,24.284184,13.788000,73.241000,19.232000,...,0.477000,0.517000,0.257500,114.701590,76.989127,6.09000,6.50350,14.879300,15.410320,8.571637
std,154.058467,154.058467,0.460098,5.44982,11.445212,6.044243,4.132187,1.832958,4.098941,1.740601,...,0.499596,0.499836,0.437366,7.564600,6.085313,4.23094,4.37362,3.641161,3.270965,2.217999
min,1.000000,1.000000,0.000000,20.00000,30.739215,136.539081,11.939138,11.000000,13.000000,16.000000,...,0.000000,0.000000,0.000000,11.525778,7.680842,0.00000,0.00000,0.000000,0.000000,0.000000
25%,132.000000,132.000000,0.000000,28.00000,52.248684,152.169130,21.765743,13.000000,72.000000,18.000000,...,0.000000,0.000000,0.000000,109.564746,72.433707,3.00000,3.00000,13.000000,13.000000,7.099641
50%,267.000000,267.000000,0.000000,31.00000,58.538632,156.433674,24.188981,14.000000,72.000000,18.000000,...,0.000000,1.000000,0.000000,114.558163,78.340745,5.00000,6.00000,15.000000,16.000000,8.434753
75%,395.000000,395.000000,1.000000,35.00000,65.519518,160.064790,26.600461,15.000000,74.000000,20.000000,...,1.000000,1.000000,1.000000,120.190386,81.186301,8.25000,9.00000,18.000000,18.000000,9.876932
max,541.000000,541.000000,1.000000,48.00000,113.379053,180.388539,40.449415,18.000000,82.000000,28.000000,...,1.000000,1.000000,1.000000,144.980616,104.267012,22.00000,20.00000,24.000000,24.000000,18.675452

 missing values

Sl. No                    0
Patient File No.          0
PCOS (Y/N)                0
 Age (yrs)                0
Weight (Kg)               0
Height(Cm)                0
BMI                       0
Blood Group               0
Pulse rate(bpm)           0
RR (breaths/min)          0
Hb(g/dl)                  0
Cycle(R/I)                0
Cycle length(days)        0
Marraige Status (Yrs)     3
Pregnant(Y/N)             0
No. of abortions          0
  I   beta-HCG(mIU/mL)    0
II    beta-HCG(mIU/mL)    0
FSH(mIU/mL)               0
LH(mIU/mL)                0
FSH/LH                    0
Hip(inch)                 0
Waist(inch)               0
Waist:Hip Ratio           0
TSH (mIU/L)               0
AMH(ng/mL)                0
PRL(ng/mL)                0
Vit D3 (ng/mL)            0
PRG(ng/mL)                0
RBS(mg/dl)                0
Weight gain(Y/N)          0
hair growth(Y/N)          0
Skin darkening (Y/N)      0
Hair loss(Y/N)            0
Pimples(Y/N)              0
Fast food (Y/N)           0
Reg.Exercise(Y/N)         0
BP _Systolic (mmHg)       0
BP _Diastolic (mmHg)      0
Follicle No. (L)          0
Follicle No. (R)          0
Avg. F size (L) (mm)      0
Avg. F size (R) (mm)      0
Endometrium (mm)          0
dtype: int64

Duplicate values

np.int64(0)

# Data cleaning and preparation
1. column names are cleaned beacause original names have spaces and symbols
2. duplicate rows are removed 
3. numeric looking text and columns are converted inot numeric formet 
4. missing numeric values are filled with median because it can occurs extreme values exits
5. identifier columns are removed becaue serial numbers and patiendts file  numbers do not explain pcos patterns

In [3]:
data=df.copy()
data.columns = (
    data.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)
#remove korbe duplicate rows gulake

before_rows = data.shape[0]
data = data.drop_duplicates()
after_rows = data.shape[0]

# convert korbe text columns to numbers

text_numeric_cols = ["ii_beta_hcg_miu_ml", "amh_ng_ml"]
for col in text_numeric_cols:
    data[col] = pd.to_numeric(data[col], errors="coerce")

    
# missing numeric values k median diye fill korbe

numeric_cols = data.select_dtypes(include=["int64", "float64"]).columns
for col in numeric_cols:
    if data[col].isnull().sum() > 0:
        data[col] = data[col].fillna(data[col].median())

# identifier columns drop korbe
data = data.drop(columns=["sl_no", "patient_file_no"], errors="ignore")

print("Duplicate rows removed:", before_rows - after_rows)
print("Cleaned dataset shape:", data.shape)
print("\nMissing values after cleaning:")
display(data.isnull().sum())

Duplicate rows removed: 0
Cleaned dataset shape: (2000, 42)

Missing values after cleaning:

pcos_y_n               0
age_yrs                0
weight_kg              0
height_cm              0
bmi                    0
blood_group            0
pulse_rate_bpm         0
rr_breaths_min         0
hb_g_dl                0
cycle_r_i              0
cycle_length_days      0
marraige_status_yrs    0
pregnant_y_n           0
no_of_abortions        0
i_beta_hcg_miu_ml      0
ii_beta_hcg_miu_ml     0
fsh_miu_ml             0
lh_miu_ml              0
fsh_lh                 0
hip_inch               0
waist_inch             0
waist_hip_ratio        0
tsh_miu_l              0
amh_ng_ml              0
prl_ng_ml              0
vit_d3_ng_ml           0
prg_ng_ml              0
rbs_mg_dl              0
weight_gain_y_n        0
hair_growth_y_n        0
skin_darkening_y_n     0
hair_loss_y_n          0
pimples_y_n            0
fast_food_y_n          0
reg_exercise_y_n       0
bp_systolic_mmhg       0
bp_diastolic_mmhg      0
follicle_no_l          0
follicle_no_r          0
avg_f_size_l_mm        0
avg_f_size_r_mm        0
endometrium_mm         0
dtype: int64

#  Feature Engineering

In [5]:
#  readable PCOS status
data["pcos_status"] = np.where(data["pcos_y_n"] == 1, "PCOS", "No PCOS")

#  total follicle count korbe
data["total_follicles"] = data["follicle_no_l"] + data["follicle_no_r"]

#  LH/FSH ratio ber korbe using NumPy
data["lh_fsh_ratio"] = np.where(
    data["fsh_miu_ml"] > 0,
    data["lh_miu_ml"] / data["fsh_miu_ml"],
    np.nan
)

#  age group korbe
data["age_group"] = pd.cut(
    data["age_yrs"],
    bins=[0, 25, 30, 35, 40, 100],
    labels=["<=25", "26-30", "31-35", "36-40", "40+"]
)

#  BMI group korbe
data["bmi_group"] = pd.cut(
    data["bmi"],
    bins=[0, 18.5, 25, 30, 100],
    labels=["Underweight", "Normal", "Overweight", "Obese"]
)

# symptom and lifestyle score
symptom_lifestyle_cols = [
    "weight_gain_y_n",
    "hair_growth_y_n",
    "skin_darkening_y_n",
    "hair_loss_y_n",
    "pimples_y_n",
    "fast_food_y_n"
]

data["symptom_lifestyle_score"] = data[symptom_lifestyle_cols].sum(axis=1)

# follicle level
data["follicle_level"] = pd.cut(
    data["total_follicles"],
    bins=[-1, 8, 16, 100],
    labels=["Low", "Medium", "High"]
)

display(data[[
    "pcos_status", "total_follicles", "lh_fsh_ratio",
    "age_group", "bmi_group", "symptom_lifestyle_score",
    "follicle_level"
]].head(100))

,pcos_status,total_follicles,lh_fsh_ratio,age_group,bmi_group,symptom_lifestyle_score,follicle_level
0,No PCOS,6,0.415789,26-30,Normal,2.0,Low
1,No PCOS,5,0.600000,36-40,Overweight,3.0,Low
2,No PCOS,2,0.539286,36-40,Normal,0.0,Low
3,PCOS,2,0.941406,26-30,Overweight,3.0,Low
4,No PCOS,7,0.148454,31-35,Normal,0.0,Low
...,...,...,...,...,...,...,...
95,No PCOS,6,0.088136,31-35,Overweight,3.0,Low
96,No PCOS,18,0.353211,31-35,Overweight,1.0,High
97,No PCOS,8,0.524436,26-30,Overweight,0.0,Low
98,No PCOS,25,0.719677,31-35,Overweight,3.0,High
99,PCOS,13,0.100000,26-30,Overweight,6.0,Medium

## 4. Data Analysis